---
title: "impression-evaluation"
author: "Ayaka Kawabe"
date: '2024-01-09'
output: html_document
---

# データ読み込み

```{r}
personality<-read.csv("csv/personality.csv",header = T)
functional<-read.csv("csv/functional.csv",header = T)
charm<-read.csv("csv/charm.csv",header=T)
```

# 人格的印象
```{r}
head(personality)
```
## 基礎統計量

### 分割なし
```{r}
print("標準偏差",quote=F)
sd(personality$no_split)
print("最小値　第一四分位　中央値　平均値　第三四分位　最大値",quote=F)
summary((personality$no_split))
```

### 分割あり
```{r}
print("標準偏差",quote=F)
sd(personality$split)
print("最小値　第一四分位　中央値　平均値　第三四分位　最大値",quote=F)
summary((personality$split))
```

## グラフ
```{r}
library(ggplot2)
library(ggbeeswarm)
library("ggsignif")
library(ggpubr)
```


```{r}
personality_plot_data<-data.frame("dependent"=c(rep("no split",max(personality$ID)),rep("split",max(personality$ID))),"score"=c(personality$no_split,personality$split))
head(personality_plot_data)
tail(personality_plot_data)
```


```{r}
ggplot(personality_plot_data,aes(x = dependent,y = score,fill=dependent))+geom_bar(stat = "summary",fun = "mean",position = position_dodge(width = 0.9),width = 0.5)+stat_summary(geom = "point", shape = 4,fun = "mean", color = "black",size=2.8)+stat_summary(geom = "errorbar",fun.data = "mean_sd",width = 0.1)+geom_beeswarm(cex = 1.2,show.legend = FALSE)+ 
  #検定結果によって変わる
  geom_text(aes(x = 1.5, y = 7.7, label = "***")) + 
  geom_segment(x = 1, xend = 1, y = 7.5, yend = 7.2) +
  geom_segment(x = 1, xend = 2, y = 7.5, yend = 7.5) +
  geom_segment(x = 2, xend = 2, y = 7.5, yend = 7.2) + theme_minimal()
```

## 分析

### t検定（母平均の差の検定）

分割あり/なしの分散が等しいとき
```{r}
t.test(personality$no_split,personality$split,paired = T,alternative = "two.sided",var.equal = T,conf.level = 0.95)
```

分割あり/なしの分散が異なるとき
```{r}
t.test(personality$no_split,personality$split,paired = T,alternative = "two.sided",var.equal = F,conf.level = 0.95)
```
### ウィルコクスンの符号付き順位検定

```{r}
wilcox.test(personality$no_split,personality$split,paired = T,alternative = "two.sided")
```



# 機能的印象
```{r}
head(functional)
```

## 基礎統計量

### 分割なし
```{r}
print("標準偏差",quote=F)
sd(functional$no_split)
print("最小値　第一四分位　中央値　平均値　第三四分位　最大値",quote=F)
summary((functional$no_split))
```

### 分割あり
```{r}
print("標準偏差",quote=F)
sd(functional$split)
print("最小値　第一四分位　中央値　平均値　第三四分位　最大値",quote=F)
summary((functional$split))
```

## 分析

### t検定（母平均の差の検定）

分割あり/なしの分散が等しいとき
```{r}
t.test(functional$no_split,functional$split,paired = T,alternative = "two.sided",var.equal = T,conf.level = 0.95)
```

分割あり/なしの分散が異なるとき
```{r}
t.test(functional$no_split,functional$split,paired = T,alternative = "two.sided",var.equal = F,conf.level = 0.95)
```
### ウィルコクスンの符号付き順位検定
```{r}
library(coin)
```
```{r}
functional_analysis_data<-data.frame("dependent"=factor(c(rep(0,max(functional$ID)),rep(1,max(functional$ID)))),"score"=c(functional$no_split,functional$split))
head(functional_analysis_data)
tail(functional_analysis_data)
```
0 = no split（分割なし）
1 = split（分割あり）
```{r}
wilcox_test(score ~ dependent,data=functional_analysis_data,paired = T,alternative = "two.sided",distribution="exact")
```

## グラフ

```{r}
functional_plot_data<-data.frame("dependent"=c(rep("no split",max(functional$ID)),rep("split",max(functional$ID))),"score"=c(functional$no_split,functional$split))
head(functional_plot_data)
tail(functional_plot_data)
```

```{r}
ggplot(functional_plot_data,aes(x = dependent,y = score,fill=dependent))+geom_bar(stat = "summary",fun = "mean",position = position_dodge(width = 0.9),width = 0.5)+stat_summary(geom = "point", shape = 4,fun = "median", color = "black",size=3,stroke=1.2)+stat_summary(geom = "errorbar",fun.data = "mean_sd",width = 0.1)+geom_beeswarm(cex = 1.2,show.legend = FALSE)+ 
  #検定結果によって変わる
  geom_text(aes(x = 1.5, y = 7.7, label = "***")) + 
  geom_segment(x = 1, xend = 1, y = 7.5, yend = 7.2) +
  geom_segment(x = 1, xend = 2, y = 7.5, yend = 7.5) +
  geom_segment(x = 2, xend = 2, y = 7.5, yend = 7.2) + theme_minimal()
```


# 愛嬌について

```{r}
head(charm)
```

##　基礎統計量

### 分割なし

```{r}
charm_table_no_split<-table(charm$no_split)
round(100*charm_table_no_split/sum(charm_table_no_split),2)
```

0 -> そう思わない

1 -> そう思う

### 分割あり
```{r}
charm_table_split<-table(charm$split)
round(100*charm_table_split/sum(charm_table_split),2)
```
0 -> そう思わない

1 -> そう思う

## 分析

### 母比率の差の検定
```{r}
prop.test(c(charm_table_no_split[2],charm_table_split[2]),c(sum(charm_table_no_split),sum(charm_table_split)),alternative = "two.sided",conf.level = 0.95)
```
### フィッシャーの確率検定
```{r}
charm_matrix_data<-matrix(c(charm_table_no_split,charm_table_split),nrow=2,byrow=T)
colnames(charm_matrix_data)<-c("そう思わない","そう思う")
rownames(charm_matrix_data)<-c("no split","split")
charm_matrix_data
```
```{r}
fisher.test(charm_matrix_data,conf.level = 0.95)
```

## グラフ
```{r}
charm_plot_data<-data.frame("dependent"=c("no split","no split","split","split"),"answer"=c("そう思わない","そう思う","そう思わない","そう思う"),"frequency"=c(charm_table_no_split,charm_table_split))
head(charm_plot_data)
```

```{r}
ggplot(data=charm_plot_data,aes(x=dependent,y=frequency,fill=answer))+geom_bar(position ="dodge",stat = "identity")+
  #検定結果によって変わる
  geom_text(aes(x = 1.5, y =8.7, label = "***")) + 
  geom_segment(x = 1, xend = 1, y = 8.5, yend = 8.2) +
  geom_segment(x = 1, xend = 2, y = 8.5, yend = 8.5) +
  geom_segment(x = 2, xend = 2, y = 8.5, yend = 8.2)+ theme_minimal()
```